## Sect1. TensorFlow 개요
- https://www.tensorflow.org/tutorials 

In [1]:
from IPython.display import Image

## Data Flow Graph
- Nodes in the graph represent mathematical operations
- Edges represent the multidimensional data arrays (tensors) communicated between them.

In [2]:
import tensorflow as tf
tf.__version__

'1.14.0'

## Hello TensorFlow!

In [4]:
# Create a constant op
# This op is added as a node to the default graph

hello = tf.constant("Hello, Stephanie")

# Start a TF Session
sess = tf.Session()

In [5]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [6]:
# run the op and get result
sess.run(hello)

b'Hello, Stephanie'

In [7]:
result = sess.run(hello)
type(result)

bytes

[TIP] b 'String'

- 'b' indicates Bytes literals.
- 참조 : What does the 'b' character do in front of a string literal?

In [8]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [9]:
type(sess)

tensorflow.python.client.session.Session

In [11]:
# ? tf.constant
# Creates a constant tensor.

## Computational Graph

In [15]:
# node1 = tf.constant(3.0, tf.float32)

node1 = tf.constant(4.0)
node2 = tf.constant(8.0)
# float32 is implicit

node3 = tf.add(node1, node2)
# node3 = node1 + node2

In [16]:
print("node1 :", node1)
print("node2 :", node2)
print("node3 :", node3)

node1 : Tensor("Const_3:0", shape=(), dtype=float32)
node2 : Tensor("Const_4:0", shape=(), dtype=float32)
node3 : Tensor("Add_1:0", shape=(), dtype=float32)


In [17]:
sess = tf.Session()
print("sess.run(node1, node2)\t: ", sess.run([node1, node2]))
print("sess.run(adder_node)  \t: ", sess.run(node3))

sess.run(node1, node2)	:  [4.0, 8.0]
sess.run(adder_node)  	:  12.0


In [18]:
type(node3)

tensorflow.python.framework.ops.Tensor

In [19]:
type(sess.run(node3))

numpy.float32

### TensorFlow Mechanics
- 그래프 빌드
- 세션을 통해 그래프를 실행
- 실행결과가 그래프를 업데이트

### Placeholder

In [20]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# + provides shortcut for tf.add(a,b)
adder_node = a + b

In [21]:
sess.run(adder_node, feed_dict = {a: 5, b:7.5})

12.5

In [22]:
sess.run(adder_node, feed_dict = {a: [1,4], b: [3,6]})
# 같은 행 순서 -> 1+4/ 4+6

array([ 4., 10.], dtype=float32)

In [23]:
add_and_triple = adder_node*4

In [24]:
sess.run(add_and_triple, feed_dict = {a: 5, b:7.5})

50.0

In [26]:
import tensorflow as tf

# 변수 a, b는 동적으로 지정
# a = tf.placeholder('float32')
# b = tf.placeholder('float32')

a = tf.placeholder('int32')
b = tf.placeholder('int32')

# multiply 함수는 입력된 정수 a와 b의 곱셈을 반환한다.
# y = tf.mul(a,b)

y = tf.multiply(a,b)

sess = tf.Session()

print("tf.mul({a}, {b}) : {y}".format(
    a = 30, b = 40,
    y= sess.run(y, feed_dict = {a:30, b:40})
))

tf.mul(30, 40) : 1200


### Constant & Variable

In [31]:
#first_session_only_tensorflow.py
import tensorflow as tf

x = tf.constant(200, name = 'x')
y = tf.Variable(x*2, name = 'y')

# model = tf.global_variables_initializer()
model = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(model)
    print("Check the variable : \n- constant x: {x} \n- Variable y : {y}".format
         ( x = sess.run(x),
             y = sess.run(y)
         ))

Check the variable : 
- constant x: 200 
- Variable y : 400


### Everything is Tensor
- Tensor Ranks, Shapes, and Types
- n차원 Array == n차원 Tensor

#### # a rank 0 tensor; this is a scalar with shape [] 3 # a rank 1 tensor; this is a vector with shape [3] [1. ,2., 3.] # a rank 2 tensor; a matrix with shape [2, 3] [[1., 2., 3.], [4., 5., 6.]] # a rank 3 tensor with shape [2, 1, 3] [[[1., 2., 3.]], [[7., 8., 9.]]]

In [32]:
rank0 = 3
rank0

3

In [33]:
rank1 = [1. ,2., 3.]
rank1
#1차원

[1.0, 2.0, 3.0]

In [34]:
rank2 = [[1., 2., 3.], 
         [4., 5., 6.]]
rank2
#2차원

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [35]:
rank3 = [
            [
                [1., 2., 3.]
            ], 
            [
                [7., 8., 9.]
            ]
] 
rank3
#3차원

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

## 텐서플로우 연산

In [36]:
import tensorflow as tf
import numpy as np

In [37]:
tensor_1d = np.array([1.2, 3.4, 5.6, 7.8])
tensor_1d

array([1.2, 3.4, 5.6, 7.8])

In [38]:
tensor_2d = np.arange(16).reshape((4,4))
tensor_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
sess = tf.Session()
tf_tensor_1d = tf.convert_to_tensor(tensor_1d,dtype=tf.float64)
tf_tensor_2d = tf.convert_to_tensor(tensor_2d,dtype=tf.float64)

In [40]:
sess.run(tf_tensor_1d)

array([1.2, 3.4, 5.6, 7.8])

In [41]:
sess.run(tf_tensor_1d[0])

1.2

In [42]:
sess.run(tf_tensor_1d[2:])

array([5.6, 7.8])

In [43]:
sess.run(tf_tensor_2d)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [44]:
#sess.run(tf_tensor_2d[3][3])
sess.run(tf_tensor_2d[3, 3])

15.0

In [45]:
sess.run(tf_tensor_2d[1:3, 1:3])

array([[ 5.,  6.],
       [ 9., 10.]])

In [46]:
import tensorflow as tf
import numpy as np

# 3x3 행렬
matrix1 = np.array([(1, 1, 1), (1, 1, 1), (1, 1, 1)])
matrix2 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)])

# constant, 텐서 자료 구조로 변환
# matrix1 = tf.constant(matrix1)
# matrix2 = tf.constant(matrix2)
matrix1 = tf.constant(matrix1, dtype='int32')
matrix2 = tf.constant(matrix2, dtype='int32')

# 행렬곱과 행렬합 계산
matrix_mul = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)

# 행렬의 행렬식(determinant)
matrix3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype='float32')
print('matrix3 = {}'.format(matrix3))

matrix_dtm = tf.matrix_determinant(matrix3)
print('matrix_dtm = {}'.format(matrix_dtm))

matrix3 = [[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
matrix_dtm = Tensor("MatrixDeterminant:0", shape=(), dtype=float32)


In [47]:
# 세션을 열고 그래프 연산
with tf.Session() as sess:
    result1 = sess.run(matrix_mul)
    result2 = sess.run(matrix_sum)
    result3 = sess.run(matrix_dtm)
    
    # tensorboard for graph
    # writer = tf.summary.FileWriter("./graph/sect01", sess.graph)

# 연산 결과 출력
print('matrix_mul = {}'.format(result1))
print('matrix_sum = {}'.format(result2))
print('matrix_dtm = {}'.format(result3))

matrix_mul = [[6 6 6]
 [6 6 6]
 [6 6 6]]
matrix_sum = [[3 3 3]
 [3 3 3]
 [3 3 3]]
matrix_dtm = 55.99999237060547


In [48]:
! pip install tensorboard