## NumPy Basics
​
### NumPy 는 Numerical Python 의 줄임말

#### NumPy 제공 기능
- 빠르고 메모리를 효율적으로 사용하며 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열인 ndarray 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선형대수, 난수발생기, 푸리에 변환 기능
- C, C++, FORTRAN으로 쓰여진 코드를 통합하는 도구

In [3]:
from IPython.display import Image
from numpy.random import randn
import numpy as np

### 1. The NumPy ndarray: a multidimensional array object
- 다차원 배열 객체

In [7]:
data = randn(2,3)
#2행 3열인 행렬 도출. Parameter가 2개 이니 2차원, 만약 comma가 하나 더 늘어나면 +1차원씩 진행됨
data

array([[-0.94841702, -0.10605421, -1.738294  ],
       [-1.49196456, -0.53579888, -0.58664613]])

In [8]:
## array = list로 생각해주면 편하다.
data*10

array([[ -9.48417024,  -1.0605421 , -17.38294004],
       [-14.91964563,  -5.35798883,  -5.8664613 ]])

In [9]:
data+data

array([[-1.89683405, -0.21210842, -3.47658801],
       [-2.98392913, -1.07159777, -1.17329226]])

In [10]:
data*2

array([[-1.89683405, -0.21210842, -3.47658801],
       [-2.98392913, -1.07159777, -1.17329226]])

In [11]:
data

array([[-0.94841702, -0.10605421, -1.738294  ],
       [-1.49196456, -0.53579888, -0.58664613]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype #실수형 64비트라는 뜻

dtype('float64')

### Creating ndarrays

In [14]:
data1 = [3,2,7,9,4.2,7.2,7.9,0] #같은 데이터 타입으로 x.x형으로 되어 있음
arr1 = np.array(data1)
arr1

array([3. , 2. , 7. , 9. , 4.2, 7.2, 7.9, 0. ])

In [15]:
data2 = [[1,2,3,4,5],[6,7,8,9,10]]
arr2 = np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
arr2.ndim #dimension구하기(number of dimension)

2

In [16]:
arr2.dtype #integer 32bit

dtype('int32')

In [17]:
arr1.dtype

dtype('float64')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,6)) #two braces
#6열 3행 -> 뒤에서 부터 읽기

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2,3,2))
#2열 3행짜리가 2개 있다. (뒤에서 부터 읽으면 됨)

array([[[1.15175375e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.92966904e-033]],

       [[4.22279424e-090, 6.11525883e+169],
        [1.55113138e+184, 1.52823587e+160],
        [3.99910963e+252, 1.46030983e-319]]])

In [23]:
####[Tip] np.empty 
#np.empty는 0으로 초기화된 배열을 반환하지 않는다. 
#대부분 empty는 초기화되지 않은 값으로 채워진 배열을 반환한다.

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays 

In [28]:
arr1 = np.array([1,2,3], dtype=np.float64)
#arr1 #아래와 같이 실수형으로 변환(x.x식)
arr1

array([1., 2., 3.])

In [29]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [35]:
arr2 = np.array([1,2,3], dtype = np.int32)

arr2.dtype

dtype('int32')

In [36]:
arr2

array([1, 2, 3])

In [37]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [38]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [39]:
arr

array([1, 2, 3, 4, 5])

In [40]:
float_arr

array([1., 2., 3., 4., 5.])

In [41]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [42]:
#[Tip] astype 
#astype을 호출하면 새로운 dtype이 이전 dtype과 같아도 항상 새로운 배열을 생성(데이터를 복사)한다. 
#float64나 float32 같은 부동소수점은 근사값이라는 사실을 염두에 두는게 중요하다.

In [43]:
# astype을 사용하여 숫자로 변환
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [45]:
#문자에서 숫자로 astype바꾸기
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [7]:
int_array=np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [8]:
int_array.astype(calibers.dtype)
#int_array를 caliber과 같은 float타입으로 변형

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
# u4는 uint32와 동일 => 이거는 거의 쓰지 않는다. 
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([2596562064,        452, 1812161538, 2080668928, 1795324929,
       1952215810, 2097185537, 2684713989], dtype=uint32)

### Operations between arrays and scalars
#### 배열과 스칼라간의 연산

In [10]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]]) 
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
#배열은 행렬의 곱과 같이 계산 되지는 않는다.
#e.g) (2*3) (3*2)의 행렬이 되야 계산되어지는데, 아래 예시들을 보면 그냥 각각의 숫자에 대해서 계산을 해준다는 것을 볼 수 있다.

arr*arr #각 인자에 대해 제곱해줌

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [12]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [14]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Basic indexing and slicing
#### 색인과 슬라이싱 기초

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [20]:
arr[5:8]= 12
arr
# 5-8번 사이의 수를 12로 치환해준다

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [21]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [22]:
arr_slice[1] = 12345
arr
#arr_slice 값에서 index1의 값만 12345로 치환

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [23]:
arr_slice[:] = 64
arr
####arr_slice 값에서 모든값을 64로 치환

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [24]:
#[Tip] 슬라이스 복사본 
#만약에 뷰 대신 ndarray 슬라이스의 복사본을 얻고 싶다면 arr[5:8].copy()를 사용해서 명시적으로 배열을 복사하면 된다.

In [25]:
#### 2차원 배열

In [26]:
# NumPy 배열에서 요소 색인하기
Image(bpc.Figure4_1)

NameError: name 'bpc' is not defined

In [27]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
##index와 같이 이해

array([7, 8, 9])

In [28]:
arr2d[0][2]

3

In [29]:
#위의 값과 같은 이야기/식 = [0][2]나 [0, 2] 같다.
arr2d[0, 2]

3

#### 3차원 배열

In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
arr3d[0]
#위의 행렬에서 1번째 행 index

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[1, 0]
#index 이용 -> 2번째 행 [1], 첫번째- 

array([7, 8, 9])

#### Indexing with slices
##### 슬라이스 색인

In [36]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [38]:
# 2차원 배열 슬라이싱
Image(bpc.Figure4_2)

NameError: name 'bpc' is not defined

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2d[:2, 1:] #첫번째는 행 짤라오고, 두번째는 열자른다

array([[2, 3],
       [5, 6]])

In [42]:
arr2d[1, :2]

array([4, 5])

In [43]:
arr2d[2, :1]

array([7])

In [44]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [45]:
arr2d[:2, 1:] = 0

In [46]:
arr2d
#0으로 바뀐 곳 보기 

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean indexing
#### 불리언 색인

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [49]:
data = randn(7,4)
data

array([[ 0.32800936,  0.14641295,  0.35849631, -0.22816469],
       [-0.11830023,  0.31835446,  0.53180358, -1.03259305],
       [ 0.45437265, -1.00676299,  2.97104326,  0.56265106],
       [ 0.41465843, -0.50629287,  1.82945747,  1.48043787],
       [-0.11005117,  1.20532085,  0.60611283, -1.09587875],
       [-0.71929027,  0.32329371, -0.47652095,  0.64071455],
       [-1.53045269,  0.13534535, -0.06780026,  0.5090183 ]])

In [50]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [51]:
data[names =='Bob']
#위에 true 값만 가져옴 [0][3]

array([[ 0.32800936,  0.14641295,  0.35849631, -0.22816469],
       [ 0.41465843, -0.50629287,  1.82945747,  1.48043787]])

In [52]:
data[names == 'Bob', 2:]
#위에서 가져온 값에서 열 분리

array([[ 0.35849631, -0.22816469],
       [ 1.82945747,  1.48043787]])

In [53]:
data[names == 'Bob', 3]

array([-0.22816469,  1.48043787])

In [54]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [55]:
data[-(names == 'Bob')]
#-더이상 못씀

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

In [56]:
#[Tip] NumPy Boolean Negative 
#'-' 연산자는 사용하지 않으며, ~ 혹은 Logical Not 함수를 대신 사용한다.

In [57]:
data[~(names == 'Bob')]

array([[-0.11830023,  0.31835446,  0.53180358, -1.03259305],
       [ 0.45437265, -1.00676299,  2.97104326,  0.56265106],
       [-0.11005117,  1.20532085,  0.60611283, -1.09587875],
       [-0.71929027,  0.32329371, -0.47652095,  0.64071455],
       [-1.53045269,  0.13534535, -0.06780026,  0.5090183 ]])

In [58]:
data[ (names != 'Bob')]
#위와 같음 ~ 혹은 ! 쓰기

array([[-0.11830023,  0.31835446,  0.53180358, -1.03259305],
       [ 0.45437265, -1.00676299,  2.97104326,  0.56265106],
       [-0.11005117,  1.20532085,  0.60611283, -1.09587875],
       [-0.71929027,  0.32329371, -0.47652095,  0.64071455],
       [-1.53045269,  0.13534535, -0.06780026,  0.5090183 ]])

In [59]:
data

array([[ 0.32800936,  0.14641295,  0.35849631, -0.22816469],
       [-0.11830023,  0.31835446,  0.53180358, -1.03259305],
       [ 0.45437265, -1.00676299,  2.97104326,  0.56265106],
       [ 0.41465843, -0.50629287,  1.82945747,  1.48043787],
       [-0.11005117,  1.20532085,  0.60611283, -1.09587875],
       [-0.71929027,  0.32329371, -0.47652095,  0.64071455],
       [-1.53045269,  0.13534535, -0.06780026,  0.5090183 ]])

In [60]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [61]:
data[mask]

array([[ 0.32800936,  0.14641295,  0.35849631, -0.22816469],
       [ 0.45437265, -1.00676299,  2.97104326,  0.56265106],
       [ 0.41465843, -0.50629287,  1.82945747,  1.48043787],
       [-0.11005117,  1.20532085,  0.60611283, -1.09587875]])

In [62]:
data[data < 0] = 0
data

array([[0.32800936, 0.14641295, 0.35849631, 0.        ],
       [0.        , 0.31835446, 0.53180358, 0.        ],
       [0.45437265, 0.        , 2.97104326, 0.56265106],
       [0.41465843, 0.        , 1.82945747, 1.48043787],
       [0.        , 1.20532085, 0.60611283, 0.        ],
       [0.        , 0.32329371, 0.        , 0.64071455],
       [0.        , 0.13534535, 0.        , 0.5090183 ]])

In [63]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.31835446, 0.53180358, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.32329371, 0.        , 0.64071455],
       [0.        , 0.13534535, 0.        , 0.5090183 ]])

### Fancy indexing
#### 팬시 색인
- 팬시 색인은 정수 배열을 사용한 색인을 설명하기 위해 NumPy에서 차용한 단어다.

In [65]:
arr = np.empty((6,4))
for i in range(6):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [66]:
arr[3]

array([3., 3., 3., 3.])

In [67]:
arr[4,3]

4.0

- 특정한 순서로 로우를 선택하고 싶다면, 그냥 원하는 순서가 명시된 정수가 담긴 ndarray나 리스트를 넘기면 된다.

In [69]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [71]:
arr[[-3, -5, -6]]

array([[3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

- 다차원 색인 배열을 넘기는 것은 조금 다르게 동작
- 각각의 색인 튜를에 대응하는 1차원 배열을 선택한 후, reshape 시킨다.

In [72]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4)) #0-32까지의 숫자, 8행 4열로 배열
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

#### (1, 0), (5, 3), (7, 1), (2, 2) 에 대응하는 요소 선택

In [73]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [74]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [75]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]
#위와 같은 함수 - 단지 ix함수를 이용하여 구함. 
#1*(0,3,1,2) -> 5*(0.3.1.2) 순으로 진행 ~

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing arrays and swapping axes

#### 배열 전치와 축 바꾸기

- 배열 전치는 데이터를 복사하지 않고 데이터 모양이 바뀐 뷰를 반환하는 특별한 기능
- ndarray는 transpose 메소드와 T라는 이름의 특수한 속성을 가진다.
- 다차원 배열의 경우 transpose 메소드는 튜플로 축 번호를 받아서 치환한다.

In [77]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [79]:
arr = np.random.randn(6, 3)
arr

array([[-1.0570751 , -0.72458964, -0.98323211],
       [-0.4102975 ,  0.79969553,  1.74306384],
       [-0.61772498,  1.74637293,  0.30690388],
       [ 1.52435792, -0.65029276, -0.39078075],
       [ 0.98121003,  1.74667301, -1.84193376],
       [-0.75416336, -2.26817114, -1.00237042]])

In [80]:
np.dot(arr.T, arr)
#3행 3열로 값이 나온다 까지만 설명 -> in this case, (3*6)*(6*3)


array([[ 5.52253853,  1.79220013, -1.51246933],
       [ 1.79220013, 12.8327091 ,  1.95274236],
       [-1.51246933,  1.95274236,  8.64938293]])

In [83]:
?np.dot

In [84]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [85]:
arr.transpose((1, 0, 2))
#이해 안가도 넘어가기- 

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [86]:
?arr.transpose

In [87]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [88]:
arr.swapaxes(1, 2)
#original form: 2,2,4 (1번째 index와 2번째 index 바꾸어주기)
#인덱스 (2,2,4) -> (2,4,2)로 바꾸어줌 

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])